require:
  - rubicon-rake
  - rubicon-rspec
  - rubicon-performance
  - rubicon-rails
AllCops:
  TargetRubyVersion: 3
  NewCops: enable
Layout/AccessModifierIndentation:
  EnforcedStyle: outset
Layout/LineLength:
  AllowURI: true
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Lint/Void:
  Enabled: true
Metrics/BlockLength:
  Max: 64
  Exclude:
    - spec/**/*.rb
Metrics/BlockNesting:
  Max: 16
Metrics/MethodLength:
  CountComments: false
  Max: 32
Metrics/ModuleLength:
  Max: 328
Metrics/ParameterLists:
  Max: 12
  CountKeywordArgs: true
Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    map: collect
    map!: collect!
    reduce: inject
    find: detect
    find_all: select
Style/Documentation:
  Enabled: true
Style/DoubleNegation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/NumericPredicate:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Transform: AWS::Serverless-2016-10-31